# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - AlphaTech

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd FDS/
          pip install -r requirements.txt
          npm ci
          cd ..
        
      - name: Run local server
        run: |
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
    
      - name: Cleaning testing files
        run: |
          cd FDS/
          rm .env
          rm -f db.sqlite3
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules
          cd ..
          
      - name: Zip artifact for deployment
        run: |
          cd FDS/
          zip release.zip ./* -r
          cd ..
          mv FDS/release.zip 
        
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_29FB121ADEDE426182AD25EBD81C6AE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21EFF303154A44C7B39AF8968CF8CD6E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D1D317BE11B4FB6B76612741018F5FA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AlphaTech'
          slot-name: 'Production'
          